//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assignment()
        {
            this.Expectation = new HashSet<Expectation>();
            this.ExpectationEvaluate = new HashSet<ExpectationEvaluate>();
            this.ExpectationEvaluate1 = new HashSet<ExpectationEvaluate>();
        }
    
        public string AssignmentId { get; set; }
        public string Name { get; set; }
        public string Info { get; set; }
        public string LectureId { get; set; }
        public System.DateTime DeliveryDate { get; set; }
    
        public virtual Lecture Lecture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expectation> Expectation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpectationEvaluate> ExpectationEvaluate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpectationEvaluate> ExpectationEvaluate1 { get; set; }
    }
}
