//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expectation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expectation()
        {
            this.ExpectationEvaluate = new HashSet<ExpectationEvaluate>();
        }
    
        public string ExpectedId { get; set; }
        public string ExpectedType { get; set; }
        public string ExpectedValue { get; set; }
        public string InputTypye { get; set; }
        public string InputValue { get; set; }
        public string AssignmentId { get; set; }
        public string Factor { get; set; }
    
        public virtual Assignment Assignment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpectationEvaluate> ExpectationEvaluate { get; set; }
    }
}
