//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LectureStudent
    {
        public string LectureStudentId { get; set; }
        public string LectureId { get; set; }
        public string StudentId { get; set; }
    
        public virtual Lecture Lecture { get; set; }
        public virtual Student Student { get; set; }
    }
}
