//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EvaluationSystemEntities2 : DbContext
    {
        public EvaluationSystemEntities2()
            : base("name=EvaluationSystemEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assignment> Assignment { get; set; }
        public virtual DbSet<Expectation> Expectation { get; set; }
        public virtual DbSet<ExpectationEvaluate> ExpectationEvaluate { get; set; }
        public virtual DbSet<Lecture> Lecture { get; set; }
        public virtual DbSet<Lecturer> Lecturer { get; set; }
        public virtual DbSet<Lecturer_Lecuture> Lecturer_Lecuture { get; set; }
        public virtual DbSet<LectureStudent> LectureStudent { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
