//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public string NotificationId { get; set; }
        public string LecturerId { get; set; }
        public string LectureId { get; set; }
        public string ContentLink { get; set; }
        public string Content { get; set; }
    
        public virtual Lecture Lecture { get; set; }
        public virtual Lecturer Lecturer { get; set; }
    }
}
